spring:
  application:
    name: ms-materials
  jpa:
    hibernate: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${PG_URL:jdbc:postgresql://localhost:5432/db_materials}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:root}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /ms-materials/index.html
  api-docs:
    path: /ms-materials
  packages-to-scan: io.github.materialcontrol.ms_materials.controllers