CREATE TABLE tb_item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(60) UNIQUE,
    status      VARCHAR(11) NOT NULL,
    material_id BIGINT      NOT NULL,
    FOREIGN KEY (material_id) REFERENCES tb_material (id)
);