CREATE TABLE tb_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(100)       NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(60)        NOT NULL,
    role     VARCHAR(20)        NOT NULL
);