spring:
  application:
    name: ms-cloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true