spring:
  application:
    name: ms-users
  jpa:
    hibernate: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${PG_URL:jdbc:postgresql://localhost:5432/db_users}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:root}

springdoc:
  swagger-ui:
    path: /ms-users/index.html
  api-docs:
    path: /ms-users
  packages-to-scan: io.github.materialcontrol.ms_users.controllers