CREATE TABLE tb_loan
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_date     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    return_date   TIMESTAMP WITHOUT TIME ZONE,
    observation   VARCHAR(300),
    user_id       BIGINT                      NOT NULL,
    item_id       BIGINT                      NOT NULL,
    created_by    VARCHAR(255),
    modified_by   VARCHAR(255),
    created_data  TIMESTAMP WITHOUT TIME ZONE,
    modified_data TIMESTAMP WITHOUT TIME ZONE
);